import { BaseAggregateRoot } from './base.aggregate';
import {
  LicenseIssuedEvent,
  LicenseActivatedEvent,
  LicenseSuspendedEvent,
  LicenseRevokedEvent,
  LicenseExpiredEvent
} from '@veerox/events';

export enum LicenseStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED'
}

export class License extends BaseAggregateRoot {
  private constructor(
    public readonly id: string,
    public readonly organizationId: string,
    public readonly workspaceId: string,
    public readonly productId: string,
    public readonly subscriptionId: string | null,
    public licenseKey: string,
    public status: LicenseStatus,
    public readonly issuedAt: Date,
    public activatedAt: Date | null,
    public expiresAt: Date | null,
    public revokedAt: Date | null,
    public suspensionReason: string | null,
    public revocationReason: string | null,
    public version: number
  ) {
    super();
  }

  static issue(props: {
    id: string;
    organizationId: string;
    workspaceId: string;
    productId: string;
    subscriptionId?: string;
    expiresAt?: Date | null;
  }): License {
    const license = new License(
      props.id,
      props.organizationId,
      props.workspaceId,
      props.productId,
      props.subscriptionId || null,
      '', // License key generated by crypto service later
      LicenseStatus.PENDING,
      new Date(),
      null,
      props.expiresAt || null,
      null,
      null,
      null,
      1
    );
    
    // We don't emit LicenseIssuedEvent here yet because the key hasn't been signed. 
    // We emit it from the application service once the cryptographic token is attached.
    return license;
  }

  static restore(props: {
    id: string;
    organizationId: string;
    workspaceId: string;
    productId: string;
    subscriptionId: string | null;
    licenseKey: string;
    status: string;
    issuedAt: Date;
    activatedAt: Date | null;
    expiresAt: Date | null;
    revokedAt: Date | null;
    suspensionReason: string | null;
    revocationReason: string | null;
    version: number;
  }): License {
    return new License(
      props.id,
      props.organizationId,
      props.workspaceId,
      props.productId,
      props.subscriptionId,
      props.licenseKey,
      props.status as LicenseStatus,
      props.issuedAt,
      props.activatedAt,
      props.expiresAt,
      props.revokedAt,
      props.suspensionReason,
      props.revocationReason,
      props.version
    );
  }

  attachCryptographicKey(key: string): void {
    if (this.status !== LicenseStatus.PENDING) {
      throw new Error('Can only attach cryptographic key to PENDING license');
    }
    this.licenseKey = key;
    
    this.apply(
      new LicenseIssuedEvent(
        crypto.randomUUID(),
        this.organizationId,
        this.workspaceId,
        this.productId,
        this.id,
        this.licenseKey,
        this.subscriptionId ?? undefined
      )
    );
  }

  updateCryptographicKey(key: string): void {
    this.licenseKey = key;
  }

  activate(): void {
    if (this.status !== LicenseStatus.PENDING && this.status !== LicenseStatus.SUSPENDED) {
      throw new Error(`Invalid transition: Cannot activate license from ${this.status}`);
    }

    this.status = LicenseStatus.ACTIVE;
    this.activatedAt = new Date();
    this.suspensionReason = null;

    this.apply(
      new LicenseActivatedEvent(
        crypto.randomUUID(),
        this.organizationId,
        this.workspaceId,
        this.id,
        this.productId
      )
    );
  }

  suspend(reason: string): void {
    if (this.status !== LicenseStatus.ACTIVE) {
      throw new Error(`Invalid transition: Cannot suspend license from ${this.status}`);
    }

    this.status = LicenseStatus.SUSPENDED;
    this.suspensionReason = reason;

    this.apply(
      new LicenseSuspendedEvent(
        crypto.randomUUID(),
        this.organizationId,
        this.workspaceId,
        this.id,
        this.productId,
        reason
      )
    );
  }

  revoke(reason: string): void {
    if (this.status === LicenseStatus.REVOKED || this.status === LicenseStatus.EXPIRED) {
      throw new Error(`Invalid transition: Cannot revoke license from ${this.status}`);
    }

    this.status = LicenseStatus.REVOKED;
    this.revokedAt = new Date();
    this.revocationReason = reason;

    this.apply(
      new LicenseRevokedEvent(
        crypto.randomUUID(),
        this.organizationId,
        this.workspaceId,
        this.productId,
        this.id,
        reason
      )
    );
  }

  expire(): void {
    if (this.status !== LicenseStatus.ACTIVE && this.status !== LicenseStatus.SUSPENDED) {
      throw new Error(`Invalid transition: Cannot expire license from ${this.status}`);
    }

    this.status = LicenseStatus.EXPIRED;
    this.version++;

    this.apply(
      new LicenseExpiredEvent(
        crypto.randomUUID(),
        this.organizationId,
        this.workspaceId,
        this.id,
        this.productId
      )
    );
  }

  evaluateExpiration(now: Date = new Date()): boolean {
    if (this.status === LicenseStatus.ACTIVE && this.expiresAt && now >= this.expiresAt) {
      this.expire();
      return true;
    }
    return false;
  }
}
